### ISSUE TITLE
it can't use

### ISSUE THREAD

**Issue by wenwenwen888** [itsrts/pptviewer-android#8]

**Comment by wenwenwen888** [comment]
Olivephone: null
                                                             com.olivephone.office.powerpoint.c.a.a.a.b: Bad File Format.
                                                                 at com.olivephone.office.powerpoint.c.a.a.a.a(Unknown Source)
                                                                 at com.olivephone.office.powerpoint.c.a.d.d.a(Unknown Source)
                                                                 at com.olivephone.office.powerpoint.b.f.a(Unknown Source)
                                                                 at com.olivephone.office.powerpoint.b.h.a(Unknown Source)
                                                                 at com.olivephone.office.powerpoint.b.run(Unknown Source)
                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                 at java.lang.Thread.run(Thread.java:818)

**Comment by youjung-hong** [comment]
I have a same problem.

**Comment by HanAsteroid** [comment]
17257-17471/? E/Olivephone: null
                                               java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.olivephone.office.powerpoint.c.b.i.l.a' on a null object reference
                                                   at com.olivephone.office.powerpoint.a.b.e.a(Unknown Source)
                                                   at com.olivephone.office.powerpoint.a.b.e.a(Unknown Source)
                                                   at com.olivephone.office.powerpoint.a.b.n.a(Unknown Source)
                                                   at com.olivephone.office.powerpoint.a.e.c(Unknown Source)
                                                   at com.olivephone.office.powerpoint.a.e.b(Unknown Source)
                                                   at com.olivephone.office.powerpoint.a.e.b(Unknown Source)
                                                   at com.olivephone.office.powerpoint.a.b.a(Unknown Source)
                                                   at com.olivephone.office.powerpoint.a.run(Unknown Source)
                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                   at java.lang.Thread.run(Thread.java:818)

**Comment by shuprajain** [comment]
i have the same
E/Olivephone: null
              com.olivephone.office.powerpoint.c.a.a.a.b: Bad File Format.
                  at com.olivephone.office.powerpoint.c.a.a.a.a(Unknown Source)
                  at com.olivephone.office.powerpoint.c.a.d.d.a(Unknown Source)
                  at com.olivephone.office.powerpoint.b.f.a(Unknown Source)
                  at com.olivephone.office.powerpoint.b.h.a(Unknown Source)
                  at com.olivephone.office.powerpoint.b.run(Unknown Source)
                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                  at java.lang.Thread.run(Thread.java:841)

**Comment by itsrts** [comment]
I can't help as not maintaining this project anymore.
